###  This will allow any cloud client to gain access to the discovery server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002

theGlobalProperty : All apps should see this global property
