---
###  This will allow any cloud client to gain access to the discovery server (Service Registry)
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/

theGlobalProperty : All apps should see this global property
...



---
spring:
  profiles: default
  
url : DEFAULT
...

---
spring:
  profiles: red
  
url : red
...

---
spring:
  profiles: blue
  
url : blue
...
