---
spring:
  profiles: default
lucky:
  word: Fetching words from profile [default] GITHUB environment!!!

---
spring:
  profiles: red
lucky: 
  wod: Today's word is anger.  Red can incite anger.

---
spring:
  profiles: blue
lucky: 
  wod: Today's word is clouds.  Clouds float in the blue sky.
