---
spring:
  profiles: default
today:
  wod: Today's word is nothing.  Nothing from nothing leaves nothing.

---
spring:
  profiles: red
today: 
  wod: Today's word is anger.  Red can incite anger.

---
spring:
  profiles: blue
today: 
  wod: Today's word is clouds.  Clouds float in the blue sky.
