---
words: scott, jennifer, tyler

---
spring:
  profiles: lower
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: upper
words: REASONABLE,LEAKY,SUSPICIOUS,ORDINARY,UNLIKELY
